import postgres from 'postgres';

import * as dotenv from 'dotenv';

dotenv.config();

const dbUrl = process.env.SUPABASE_DB_URL;

const adminHash = process.env.ADMIN_HASH;

if (!dbUrl) {
  throw new Error('Missing SUPABASE_DB_URL environment variable');
}

if (!adminHash) {
  throw new Error('Missing ADMIN_HASH environment variable');
}

const sql = postgres(dbUrl);

async function setup() {
  try {
    await sql`
      CREATE TABLE IF NOT EXISTS public.days (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT now(),
        date text NOT NULL,
        order_index integer NOT NULL,
        CONSTRAINT days_pkey PRIMARY KEY (id)
      );
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS public.items (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        day_id bigint NOT NULL,
        time text NULL,
        title text NOT NULL,
        short text NOT NULL,
        full text NULL,
        tag_text text NULL,
        tag_class text NULL,
        order_index integer NOT NULL,
        CONSTRAINT items_pkey PRIMARY KEY (id),
        CONSTRAINT items_day_id_fkey FOREIGN KEY (day_id) 
          REFERENCES days (id) ON DELETE CASCADE
      );
    `;

    await sql`
      ALTER TABLE public.days ENABLE ROW LEVEL SECURITY;
      
      ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
    `;

    await sql`
      CREATE OR REPLACE FUNCTION get_admin_header() 
      RETURNS text AS $$
      BEGIN
        RETURN current_setting('request.headers', true)::json->>'x-admin-code';
      EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql STABLE;
    `;

    await sql`
      DROP POLICY IF EXISTS "View Days" ON public.days;
      
      CREATE POLICY "View Days" ON public.days 
      FOR SELECT TO anon USING (true);
      
      DROP POLICY IF EXISTS "Admin Modify Days" ON public.days;
      
      CREATE POLICY "Admin Modify Days" ON public.days 
      FOR ALL TO anon 
      USING (get_admin_header() = ${adminHash})
      WITH CHECK (get_admin_header() = ${adminHash});
    `;

    await sql`
      DROP POLICY IF EXISTS "View Items" ON public.items;
      
      CREATE POLICY "View Items" ON public.items 
      FOR SELECT TO anon USING (true);
      
      DROP POLICY IF EXISTS "Admin Modify Items" ON public.items;
      
      CREATE POLICY "Admin Modify Items" ON public.items 
      FOR ALL TO anon 
      USING (get_admin_header() = ${adminHash})
      WITH CHECK (get_admin_header() = ${adminHash});
    `;

    await sql`
      CREATE OR REPLACE FUNCTION swap_day_contents(id_a bigint, id_b bigint)
      RETURNS void AS $$
      BEGIN
        IF get_admin_header() IS DISTINCT FROM ${adminHash} THEN
          RAISE EXCEPTION 'Unauthorized';
        END IF;

        UPDATE public.items 
        SET day_id = (CASE 
          WHEN day_id = id_a THEN id_b 
          WHEN day_id = id_b THEN id_a 
        END)
        WHERE day_id IN (id_a, id_b);
      END;
      $$ LANGUAGE plpgsql SECURITY DEFINER;
    `;

    console.log('Database setup completed successfully.');
    
    process.exit(0);
  } catch (err) {
    console.error('Error setting up database:', err);
    
    process.exit(1);
  }
}

setup();
